### ISSUE TITLE
summit_xl_control crashes as soon as I launch

### ISSUE THREAD

**Issue by ktiwari9** [RobotnikAutomation/summit_xl_sim#10]
I get the following error as soon as I launch the summit_xl_control to get a link between odom and base_link.
[ INFO] [1441269232.456259714, 0.241000000]: Physics dynamic reconfigure ready.
[ INFO] [1441269232.585299607, 0.371000000]: SummitXLControllerClass::starting
[summit_xl/summit_xl_robot_control-10] process has died [pid 13889, exit code -11, cmd /home/toshiba/catkin_ws/devel/lib/summit_xl_robot_control/summit_xl_robot_control __name:=summit_xl_robot_control __log:=/home/toshiba/.ros/log/664a1aea-5216-11e5-b082-e06995342d97/summit_xl-summit_xl_robot_control-10.log].
log file: /home/toshiba/.ros/log/664a1aea-5216-11e5-b082-e06995342d97/summit_xl-summit_xl_robot_control-10*.log

My tf tree is shown below. I have 2 robots. one husky and one summit so I am using a namespace for summit as summit_xl. I dont understand why is there a tf from /gazebo from /map->/odom but not via the summit_controller_node.

![frames-1](https://cloud.githubusercontent.com/assets/5789469/9654395/868bb9cc-5265-11e5-9e8f-744073c5668c.png)

**Comment by dani-carbonell** [comment]
I guess you are using Hydro, since "summit_xl_robot_control" was deprecated in Indigo. 
I also guess that you refer to the transform being published by /gazebo between /odom and /summit_xl/base_footprint.
Is this right?
Note that "summit_controller_node" does not exist in this simulation. It should only exist in the real robot of the smaller version of the SummitXL.

**Comment by RoBoLog** [comment]
Hi,
I cant make the summit_xl move in gazebo, by using rqt. I checked both the summit_xl_control.yaml file and also the urdf for the rubber wheels. the type of controller for each wheel is consitent with the hardware interface mentioned in the wheel urdf file. 

type: velocity_controllers/JointVelocityController  (controller.yaml)

<hardwareInterface>VelocityJointInterface</hardwareInterface> (wheel urdf)

I can't figure out what is wrong. Its the same case both for the summit_xl and summit_xl_omni...they do not move at all. where as   summit_xl_hls_omni moves but for that the type of controller is 
type: effort_controllers/JointEffortController

I can't figure it out this paradox...!!

Can you help please...!!
