### ISSUE TITLE
Issue when catkin_make

### ISSUE THREAD

**Issue by Enzo-M** [RobotnikAutomation/summit_xl_sim#14]
Hello,

I git cloned your repertory to my catkin_ws with : 
`git clone -b kinetic-devel https://github.com/RobotnikAutomation/summit_xl_sim/`
and then when executing : 
`catkin_make`
i got this error :

CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "gazebo_ros" with
  any of the following names:

    gazebo_rosConfig.cmake
    gazebo_ros-config.cmake

  Add the installation prefix of "gazebo_ros" to CMAKE_PREFIX_PATH or set
  "gazebo_ros_DIR" to a directory containing one of the above files.  If
  "gazebo_ros" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  summit_xl_sim/summit_xl_gazebo/CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/menassolenzo/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/menassolenzo/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:1830: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by Enzo-M** [comment]
Problem solved with : `sudo apt install --reinstall ros-kinetic-gazebo-ros` 
don't install gazebo8 it won't work

**Comment by anlorla** [comment]
`sudo apt install --reinstall ros-noetic-gazebo-ros` if your version is noetic
