### ISSUE TITLE
ERROR-SUMMIT XL- roslaunch summit_xl_sim_bringup summit_xl_complete.launch

### ISSUE THREAD

**Issue by aflores-c** [RobotnikAutomation/summit_xl_sim#16]
I have this error !!. Please help!! 
Ubuntu 14.04 LTS
ROS-Indigo

ROS@ubuntu:~/summit_ws$ roslaunch summit_xl_sim_bringup summit_xl_complete.launch
... logging to /home/andy/.ros/log/ee0a06e6-a3e2-11e7-b353-a0f3c12449d2/roslaunch-ubuntu-12412.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 696, in main
    eval_self_contained(doc)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 626, in eval_self_contained
    eval_all(doc.documentElement, macros, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 526, in eval_all
    (str(name), str(node.tagName)))
xacro.XacroException: Invalid parameter "name" while expanding macro "xacro:sensor_hokuyo_urg04lx"
while processing /home/andy/summit_ws/src/summit_xl_sim/summit_xl_gazebo/launch/summit_xl.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/home/andy/summit_ws/src/summit_xl_common/summit_xl_description/robots/summit_xl.urdf.xacro'] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py '$(find summit_xl_description)/robots/summit_xl.urdf.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file

**Comment by aflores-c** [comment]
I comment the following descriptions in summit_xl.urdf.xacro and I can run Gazebo now!! but I don't have hokuyo_base and sensor_imu in my simulation !


<xacro:sensor_hokuyo_urg04lx name="hokuyo_base" parent="base_link">
		<origin xyz="-0.0 0.0 0.33" rpy="0 0 0"/>
	</xacro:sensor_hokuyo_urg04lx>

<xacro:sensor_imu_hector name="imu" parent="base_link" >
		<origin xyz="-0.18 0.0 0.170" rpy="0 0 0"/>
	</xacro:sensor_imu_hector_is>


![summit](https://user-images.githubusercontent.com/21019828/30944726-76b2cf24-a3bf-11e7-979b-5247cbd7178f.png)

**Comment by RomanRobotnik** [comment]
Hi, thanks for reporting the issue.

I should be solved after last updates in the following packages repos(branch: indigo-devel):

https://github.com/RobotnikAutomation/summit_xl_common/
https://github.com/RobotnikAutomation/robotnik_sensors

Let me know if the problem still persists.

Román

**Comment by cheriperi** [comment]
Hi, I have the same issue for the kinetic version:
Ubuntu 16.04
Ros-kinetic

rosrun xacro xacro.py /opt/ros/kinetic/share/summit_xl_description/robots/summit_xl.urdf.xacro 
Invalid parameter "name" None None
when instantiating macro: sensor_hokuyo_urg04lx (/opt/ros/kinetic/share/summit_xl_description/robots/summit_xl.urdf.xacro)
in file: /opt/ros/kinetic/share/summit_xl_description/robots/summit_xl.urdf.xacro

it happens with the sensor_hokuyo_urg04lx, thesensor_hokuyo_utm30lx and thesensor_imu_hector by far.

Thank you in advance.

**Comment by gitakshaygupta** [comment]
Hello, 
I am using ROS on Ubuntu Kinetic 16.04. Following the process on the README file, I am stuck with the following error. I would like to know if there is a fix for it? Thanks a lot!
*****************************************

No such file or directory: /opt/ros/kinetic/share/summit_xl_description/robots/summit_xl_std.urdf.xacro None None
while processing /home/akshay/catkin_ws/src/summit_xl_sim/summit_xl_gazebo/launch/summit_xl_gazebo.launch:
while processing /home/akshay/catkin_ws/src/summit_xl_sim/summit_xl_gazebo/launch/summit_xl_one_robot.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/lib/xacro/xacro '/opt/ros/kinetic/share/summit_xl_description/robots/summit_xl_std.urdf.xacro' prefix:=summit_xl_a_ ros_planar_move_plugin:=false omni_wheels:=false --inorder] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro '$(find summit_xl_description)/robots/$(arg xacro_robot)' prefix:=$(arg prefix) ros_planar_move_plugin:=$(arg ros_planar_move_plugin) omni_wheels:=$(arg ros_planar_move_plugin) --iprnorder" name="robot_description"/>
The traceback for the exception was written to the log file

*****************************************
