### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__tf2)

### ISSUE THREAD

**Issue by zainmehdi** [RobotnikAutomation/summit_xl_sim#21]
I am trying to launch the simulation in gazebo. The compilation phase went well but during launch I keep getting the following error

> 
ImportError: dynamic module does not define module export function (PyInit__tf2)

And here is the complete output. Kindly let me know if any solution is available thanks.

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/gazebo_ros/spawn_model", line 32, in <module>
    import tf.transformations as tft
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf/__init__.py", line 28, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define module export function (PyInit__tf2)
[ INFO] [1564547659.199729206]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1564547659.200105700]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1564547659.221360613]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1564547659.221721097]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[INFO] [1564547659.228035, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[summit_xl_a/urdf_spawner_summit_model-3] process has died [pid 11002, exit code 1, cmd /opt/ros/kinetic/lib/gazebo_ros/spawn_model -x 0 -y 0 -z 0 -urdf -param robot_description -model summit_xl_a __name:=urdf_spawner_summit_model __log:=/home/zain/.ros/log/754550aa-b34c-11e9-9cce-5c5f678de2bc/summit_xl_a-urdf_spawner_summit_model-3.log].
log file: /home/zain/.ros/log/754550aa-b34c-11e9-9cce-5c5f678de2bc/summit_xl_a-urdf_spawner_summit_model-3*.log
[ INFO] [1564547660.198802804, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1564547660.227512636, 0.050000000]: Physics dynamic reconfigure ready.
[ INFO] [1564547660.286905771, 0.107000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1564547660.320738700, 0.140000000]: Physics dynamic reconfigure ready.
^C[rviz-9] killing on exit
[gazebo_gui-8] killing on exit
[gazebo-7] killing on exit
[summit_xl_a/twist_marker-6] killing on exit
[summit_xl_a/twist_mux-5] killing on exit
[summit_xl_a/controller_spawner-4] killing on exit
[summit_xl_a/robot_state_publisher-2] killing on exit
[WARN] [1564547669.847412, 9.022000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete

**Comment by Double-CC** [comment]
Errors like this are caused by python version problem.  Your tf package can only be used by python2, so just change the first line of your spawn_model script: from `#!  /usr/bin/env python` to `#! /usr/bin/env python2.7`.

**Comment by EricWang1hitsz** [comment]
> Errors like this are caused by python version problem. Your tf package can only be used by python2, so just change the first line of your spawn_model script: from `#! /usr/bin/env python` to `#! /usr/bin/env python2.7`.

It works? I tried to change spawn model script, but simulation still has error above.
