### ISSUE TITLE
pid_gains not defined

### ISSUE THREAD

**Issue by ShiJbey** [RobotnikAutomation/summit_xl_sim#22]
After downloading and installing all the dependencies for the simulator, I get the following error message when starting the sim. 

`[ERROR] [1568037865.296948751, 0.001000000]: No p gain specified for pid.  Namespace: /summit_xl_a/gazebo_ros_control/pid_gains/summit_xl_a_front_right_wheel_joint
[ERROR] [1568037865.297741982, 0.001000000]: No p gain specified for pid.  Namespace: /summit_xl_a/gazebo_ros_control/pid_gains/summit_xl_a_front_left_wheel_joint
[ERROR] [1568037865.298591089, 0.001000000]: No p gain specified for pid.  Namespace: /summit_xl_a/gazebo_ros_control/pid_gains/summit_xl_a_back_left_wheel_joint
[ERROR] [1568037865.299297377, 0.001000000]: No p gain specified for pid.  Namespace: /summit_xl_a/gazebo_ros_control/pid_gains/summit_xl_a_back_right_wheel_joint
[ERROR] [1568037865.301091322, 0.001000000]: No p gain specified for pid.  Namespace: /summit_xl_a/gazebo_ros_control/pid_gains/summit_xl_a_front_ptz_camera_pan_joint
[ERROR] [1568037865.302231992, 0.001000000]: No p gain specified for pid.  Namespace: /summit_xl_a/gazebo_ros_control/pid_gains/summit_xl_a_front_ptz_camera_tilt_joint
`
How can I fix this error? I believe it is responsible for the erratic behavior I'm seeing when trying to control the summit_xl with a gamepad. Thank you. 

If it matters, I am using ROS Melodic on Ubuntu 18.04.

**Comment by ChrisTimperley** [comment]
For what it's worth, I'm also experiencing the same problem using ROS Kinetic on Ubuntu 16.04.

**Comment by jgomezgadea** [comment]
We are using a plugin for the movement of the robot that doesn't needs a pid, so the missing pid gazebo error should be a warning (because it is not necessary in our simulation).

@ShiJbey which problem are you experiencing with the gamepad? I tested the simulation and it is working fine for me with a PS4 controller. Make sure that RViz is not publishing 0 to any cmd_vel topic through pad_teleop plugin while you are using your controller.

**Comment by ChrisTimperley** [comment]
> We are using a plugin for the movement of the robot that doesn't needs a pid, so the missing pid gazebo error should be a warning (because it is not necessary in our simulation).

That makes sense. Thanks for the quick response! :+1:
