### ISSUE TITLE
Gazebo simulation- Wheels of SUMMIT XL robot not rotating in gazebo

### ISSUE THREAD

**Issue by Eswar1991** [RobotnikAutomation/summit_xl_sim#26]
We are trying to move the summit xl robot in straight line in gazebo. Although the robot moves, the wheel doesn't rotate. The following errors pop up whenever we launch the corresponding launch file.
![Screenshot from 2020-05-25 12-15-05](https://user-images.githubusercontent.com/16931432/82787218-9707da00-9e83-11ea-9577-443b522cfcda.png)

It seems the yaml file misses the pid parameters for wheel joints. Although we tried to give the PID parameters to these joints, still the error persists and the wheels are not rotating.

Any help for this issue would be appreciated. Thanks

**Comment by RomanRobotnik** [comment]
Hi,

I guess you are running the simulation from sources.

Recently we disabled by default the use of the DiffDriveController plugin because we were not getting the desired behaviour, and we set by default use of the ros_planar.

In case you want to run the simulation by enabling the DiffDriveController you can run it with the argument ros_planar_move_plugin:=false.

```
roslaunch summit_xl_sim_bringup summit_xl_complete.launch ros_planar_move_plugin:=false
```

**Comment by Eswar1991** [comment]
Thank you for your reply. We also figured out the same. Thank you once
again.

**Comment by Eswar1991** [comment]
One quick doubt is that where is the ros planar plugin argument is linked
to ros planar controller?  We are unable to find out that link.

**Comment by RomanRobotnik** [comment]
It is linked at URDF model description level as a xacro.
All the summit_xl bases share the [summit_xl_base.gazebo.xacro](https://github.com/RobotnikAutomation/summit_xl_common/blob/kinetic-devel/summit_xl_description/urdf/bases/summit_xl_base.gazebo.xacro)

Then, in the main [robot.xacro](https://github.com/RobotnikAutomation/summit_xl_common/blob/kinetic-devel/summit_xl_description/robots/summit_xl_std.urdf.xacro) we have an argument to include it.

And finally, in the [gazebo one_robot launch](https://github.com/RobotnikAutomation/summit_xl_sim/blob/kinetic-devel/summit_xl_gazebo/launch/summit_xl_one_robot.launch)  we pass the argument here:

```
<param name="robot_description" command="$(find xacro)/xacro '$(find summit_xl_description)/robots/$(arg xacro_robot)' prefix:=$(arg prefix) **ros_planar_move_plugin:=$(arg ros_planar_move_plugin)** omni_wheels:=$(arg omni_drive) --inorder"/>
```
Hope it helps!

**Comment by Eswar1991** [comment]
Great got it. Thanks for your prompt response.

**Comment by Eswar1991** [comment]
We are trying to simulate a custom path movement of summit xl in gazebo,
and perform them on real-world using the robot.

That's why we are using the differential control drive.. is it recommended
to proceed with gazebo.? And why desired behavior is not expected with
differential drive controller in gazebo?

As we didn't find wheel rotation in ros planar, we enabled the differential
drive controller plugin. If possible, Can you please explain the reason for
not using differential drive controller plugin by default?
