### ISSUE TITLE
Gazebo- Front wheels of SUMMIT XL yields erratic motion (lifting upwards) when trying to move in straight line.

### ISSUE THREAD

**Issue by Eswar1991** [RobotnikAutomation/summit_xl_sim#27]
The objective is to rotate the wheels as the robot moves on in a straight line. To this end, we enabled the robotnik_base_control in simulation environment to control and rotate the wheels and tried to replicate the real-world motion of robot. 
However, on doing that, the robot outputs an erratic behaviour, wherein it skids and the front wheel is lifted upwards as the robot moves on. 
![image](https://user-images.githubusercontent.com/16931432/82791433-6035c200-9e8b-11ea-9bf1-b8ca93df0be4.png)

Any help on this issue is appreciated...

**Comment by RomanRobotnik** [comment]
Hi, 

I guess this issue is related to [this one](https://github.com/RobotnikAutomation/summit_xl_sim/issues/26). Please try to keep it in the same thread.

Are you using any plugin? if so, please revise my answer in the other issue.

Thanks!
