### ISSUE TITLE
robot_map is never published in simulation

### ISSUE THREAD

**Issue by rpl-as-ucl** [RobotnikAutomation/summit_xl_sim#32]
Hi all,

I run: roslaunch summit_xl_sim_bringup summit_xls_complete.launch

and it appears that robot_map is published at all.  Any clue why this may be happening?

**Comment by alex-arnal** [comment]
Hi!

By default there is not map published, you will need to set the launch arguments to run the map_server, AMCL and move_base. In the robot a arguments section you have several arguments that will help you to run that part of the software.

https://github.com/RobotnikAutomation/summit_xl_sim/blob/e73caa11e2bcde5080e8953282c020f685f419c6/summit_xl_sim_bringup/launch/summit_xls_complete.launch#L18-L23
