### ISSUE TITLE
Error docker installation

### ISSUE THREAD

**Issue by NAEE09** [RobotnikAutomation/summit_xl_sim#37]
Hello I already have docker, nvidia-docker, and nvidia driver installed but when I execute the docker/simulation-in-container-run.sh, it show the next error:

`[INFO]:    Checking tools
[SUCCESS]: All required tools are available
[INFO]:    Checking display
[SUCCESS]: Display found
[INFO]:    Checking Nvidia CUDA
[SUCCESS]: Nvidia CUDA version 11.7
ERROR]:   Couldn find a suitable testing image of nvidia docker
`

I dont know if i need another version of the docker, I am new with the docker cointainers.

Software version:
Ubuntu 20.04
docker 20.10.21
nvidia docker: nvidia/cuda 11.6.2

**Comment by ggari-robotnik** [comment]
Hello @NAEE09,

Sorry for the late reply.  I'm afraid that the script got a little bit outdated. We need to update the documentation, sorry for that.

Please install the docker compose plugin and define the following variables:
```bash
export ROS_BU_PKG="summit_xl_sim_bringup"
export ROS_BU_LAUNCH="summit_xl_complete.launch"
```
And execute it using the docker compose command:
```bash
cd docker
docker compose up
```

Please let me know if you succeeded to launch it.

**Comment by NAEE09** [comment]
Hello

Yes, it works. Thank you
